services:
  postgres:
    image: postgres:16-alpine
    container_name: insurance-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: insurance-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy

  registry-emulator:
    build:
      context: .
      dockerfile: registry-emulator/Dockerfile
    container_name: registry-emulator
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/registry_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password
    depends_on:
      postgres:
        condition: service_healthy

  insurance-service:
    build:
      context: .
      dockerfile: insurance-service/Dockerfile
    container_name: insurance-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/insurance_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password
      # Внутренний URL Keycloak для валидации JWT токенов
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/insurance-realm
      # URL эмулятора для REST-клиента
      - REGISTRY_EMULATOR_URL=http://registry-emulator:8080
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

volumes:
  postgres_data: